[build]
  publish = "public"         # O Netlify publicará a pasta 'public' como seu site
  functions = "netlify/functions" # O Netlify procurará por funções na pasta 'netlify/functions'

# A linha "python_version = "3.9"" foi removida daqui.
# O Netlify usará sua versão padrão de Python.)
